import os
import random
import datetime
import requests
import xml.etree.ElementTree as ET
from github import Github

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPOSITORY")

g = Github(GITHUB_TOKEN)

CATEGORIES = [
    "Sports", "Lifestyle", "Stock News", "Cooking", "Health", 
    "Film Industry", "Movie Review", "Anime Latest", "Technology", 
    "Business & Startups", "Global Facts"
]

def get_trending_topic(selected_category):
    try:
        url = "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en"
        response = requests.get(url, timeout=10)
        root = ET.fromstring(response.content)
        titles = [item.find('title').text for item in root.findall('.//item')]
        if titles:
            return random.choice(titles[:15]).split(" - ")[0]
    except Exception:
        pass
    return "Market & Global Dynamic System Breakthroughs"

def generate_dual_content(topic, category):
    # Expanded deep multi-paragraph fallback structure
    backup_article = f"""
    <p>The latest breakthrough events surrounding <b>{topic}</b> have taken center stage globally, drawing immense attention across key industrial and community circles.</p>
    <p>Analysts and frontline observers report that these unexpected structural adjustments are paving the way for a completely new operational framework within the broader {category} landscape.</p>
    <p>Moving forward, stakeholders emphasize the critical importance of monitoring logistical patterns and localized metrics to safely capture the momentum generated by this strategic milestone.</p>
    """
    backup_short = f"<h4>Quick Update on {topic}</h4><p>Key operational metrics regarding {topic} are rapidly expanding across dynamic networks under the {category} matrix.</p>"

    if not GEMINI_API_KEY:
        return backup_article, backup_short

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={GEMINI_API_KEY}"
    prompt = f"""
    Write an incredibly deep, professional human news summary for INFOVEX about '{topic}' in category '{category}'.
    Avoid any AI cliché words. Write exactly 3 long detailed paragraphs.
    Wrap the paragraphs inside [START_ARTICLE]...[END_ARTICLE] tags (use standard HTML p tags).
    Wrap a sharp visual short summary inside [START_SHORT]...[END_SHORT] tags using an h4 title and a single paragraph.
    """
    
    try:
        response = requests.post(url, json={"contents": [{"parts": [{"text": prompt}]}]}, timeout=15)
        res_json = response.json()
        raw_text = res_json['candidates'][0]['content']['parts'][0]['text']
        raw_text = raw_text.replace("```html", "").replace("```", "").strip()
        
        article = raw_text.split("[START_ARTICLE]")[1].split("[END_ARTICLE]")[0].strip()
        short = raw_text.split("[START_SHORT]")[1].split("[END_SHORT]")[0].strip()
        return article, short
    except Exception:
        return backup_article, backup_short

def update_platform(article_body, short_body, category, topic):
    repo = g.get_repo(GITHUB_REPO)
    contents = repo.get_contents("index.html", ref="main")
    html_code = contents.decoded_content.decode("utf-8")
    
    timestamp = datetime.datetime.now().strftime("%B %d, %Y • %I:%M %p")
    
    # Dynamic high-quality image injection link mapping
    clean_topic = topic.replace(" ", "+")
    img_tag = f'<img src="https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80" alt="News Image" style="width:100%; max-height:380px; object-fit:cover; margin-bottom:20px; border-radius:4px; border:1px solid #eee;">'
    
    # Premium structural mapping with double container unbinding system
    full_post_template = f"""
    <div class="post-card">
        <div class="meta">{timestamp} • {category}</div>
        <h2>{topic}</h2>
        <div class="preview-text">Latest developments on {topic} have emerged. Click to read the full comprehensive editorial report.</div>
        <div class="full-story">
            {img_tag}
            {article_body}
        </div>
    </div>
    """
    
    short_template = f"""
    <div class="short-card">
        <div class="short-tag">{category}</div>
        {short_body}
    </div>
    """
    
    article_placeholder = '<div id="posts-container">'
    short_placeholder = '<div class="shorts-sticky" id="shorts-container">'
    
    if article_placeholder in html_code and short_placeholder in html_code:
        html_code = html_code.replace(article_placeholder, f"{article_placeholder}\n{full_post_template}")
        html_code = html_code.replace(short_placeholder, f"{short_placeholder}\n{short_template}")
        
        repo.update_file(contents.path, f"AI Desk Update: Full Multi-View {category}", html_code, contents.sha, branch="main")
        print("🎉 Platform updated successfully with deep structures!")

if __name__ == "__main__":
    selected_category = random.choice(CATEGORIES)
    trending_topic = get_trending_topic(selected_category)
    article_html, short_html = generate_dual_content(trending_topic, selected_category)
    update_platform(article_html, short_html, selected_category, trending_topic)
