name: AI Auto Blogger

on:
  schedule:
    # Har 2 ghante me robot automatic chalega
    - cron: '0 */2 * * *'
  workflow_dispatch: # Manually chalane ke liye

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libraries
        run: |
          pip install requests PyGithub pytrends

      - name: Run AI Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python static_blogger.py
